name: CI

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'scripts/**'
      - 'LICENSE.txt'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'scripts/**'
      - 'LICENSE.txt'
      - 'README.md'

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CTEST_PARALLEL_LEVEL: 2

jobs:
  nvcc:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          method: 'network'
          sub-packages: '["nvcc"]'

      - name: Generate
        run: cmake -B build -S . -G Ninja -D CMAKE_CXX_COMPILER=nvcc -D CMAKE_SHARED_LIBRARY_LINK_C_FLAGS= -D CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS=

      - name: Build
        run: cmake --build build
        
      - name: Test
        run: ctest --test-dir build --no-tests=error
